### ISSUE TITLE
Typeutils Warnings

### ISSUE THREAD

**Issue by Patitotective** [alaviss/union#18]
Whenever you import _union_ you will get these warnings:
```nim
/home/cristobal/.nimble/pkgs/union-0.1.1/union/typeutils.nim(65, 12) Warning: compiler bug workaround; see https://github.com/nim-lang/Nim/issues/18867 [User]
/home/cristobal/.nimble/pkgs/union-0.1.1/union/typeutils.nim(67, 14) Warning: compiler bug workaround; see https://github.com/nim-lang/Nim/issues/19072 [User]
```
They haven't caused me any error but I'd prefer them to not exist.
***
Version: 0.1.1

**Comment by alaviss** [comment]
The warnings are removed as of https://github.com/alaviss/union/commit/5e22080d549bc6e44808ecbedd1b89c0df1099dc
