### ISSUE TITLE
Is there a way to iterate over the types within a union type?

### ISSUE THREAD

**Issue by ajusa** [alaviss/union#25]
Looking for something similar to fieldPairs, where you'd have a macro that unrolls the for loop into many statements, with a typedesc as the yielded value?

**Comment by alaviss** [comment]
There is something like that, checkout [`unpack()`](https://alaviss.github.io/union/union.html#unpack.m%2CT%2Cuntyped)

**Comment by ajusa** [comment]
Didn't realize it could be used that way!
For my use case, I can just declare a dummy variable with the type of the union, and then unpack it to get the type. Thank you for the very fast response and excellent library!
