### ISSUE TITLE
Generic instantiation change breaks `recCase`

### ISSUE THREAD

**Issue by Gruruya** [alaviss/union#51]
With https://github.com/nim-lang/Nim/pull/22642 this:
```
ObjectTy
  Empty
  Sym "Union"
  RecList
    RecCase
      Sym "type"
      OfBranch
        IntLit 0
        Sym "field0"
      OfBranch
        IntLit 1
        Sym "field1"
```
becomes:
```
NilLit
```

Tests now error. The error is:
```sh
union/union/uniontraits.nim(116, 33) Error: cannot get child of node kind: nnkNilLit
```

Error points to this:
https://github.com/alaviss/union/blob/a5b6d313e2290a51ee7b7e929ed0b634db1b280d/union/uniontraits.nim#L104-L106

An example of where the error occurs (first usage of `as`): https://github.com/alaviss/union/blob/a5b6d313e2290a51ee7b7e929ed0b634db1b280d/tests/treadme.nim#L6-L15

The PR added [getObjectSym](https://github.com/nim-lang/Nim/pull/22642/files#diff-251afcd01d239369019495096c187998dd6695b6457528953237a7e4a10f7138):
```nim
proc getObjectSym(t: PType): PSym =
  if tfFromGeneric in t.flags and t.typeInst.kind == tyGenericInst:
    var dummy: SkippedPtr
    result = t.typeInst[0].skipToObject(dummy).sym
  else:
    result = t.sym
```
I'm guessing this usage of `sameType` needs to be updated:
https://github.com/alaviss/union/blob/a5b6d313e2290a51ee7b7e929ed0b634db1b280d/union/uniontraits.nim#L88-L94
But I don't know how.

**Comment by metagn** [comment]
Nim change will probably be reverted

Tested `treadme` with https://github.com/nim-lang/Nim/pull/22652 and it works

**Comment by alaviss** [comment]
Looks like my little hack to see if `T` is inherited from an instance of a generic type `G` finally failed :P

I think I have a solution for this, though.

**Comment by alaviss** [comment]
Apparently I misremembered how this is done.

As described in https://github.com/nim-lang/Nim/pull/22642, old Nim uses the generic type symbol for AST, which is why I had to check directly against the generic symbol.

**Comment by metagn** [comment]
This would have also been a problem with https://github.com/nim-lang/Nim/pull/22655, thanks for fixing
